"""Application constants."""

from app.constants.agent import (
    DEFAULT_LLM_MODEL,
    DEFAULT_LLM_PROVIDER,
    DEFAULT_MAX_TOKENS,
    MAX_TITLE_LENGTH,
    TITLE_TRUNCATION_LENGTH,
    TITLE_TRUNCATION_SUFFIX,
)
from app.constants.database import (
    CLOUD_SQL_IP_TYPE_PRIVATE,
    CLOUD_SQL_IP_TYPE_PUBLIC,
    DEFAULT_MAX_OVERFLOW,
    DEFAULT_POOL_SIZE,
)
from app.constants.http import (
    HTTP_BAD_REQUEST,
    HTTP_CREATED,
    HTTP_FORBIDDEN,
    HTTP_INTERNAL_SERVER_ERROR,
    HTTP_NO_CONTENT,
    HTTP_NOT_FOUND,
    HTTP_OK,
    HTTP_TOO_MANY_REQUESTS,
    HTTP_UNAUTHORIZED,
)
from app.constants.jwt import (
    DEFAULT_ACCESS_TOKEN_EXPIRE_MINUTES,
    DEFAULT_JWT_ALGORITHM,
    DEFAULT_REFRESH_TOKEN_EXPIRE_DAYS,
    HOURS_PER_DAY,
    SECONDS_PER_DAY,
    SECONDS_PER_HOUR,
    SECONDS_PER_MINUTE,
)
from app.constants.pagination import (
    DEFAULT_PAGE,
    DEFAULT_PER_PAGE,
    MAX_PER_PAGE,
    MIN_PER_PAGE,
)
from app.constants.rate_limit import (
    CREATE_CONVERSATION_RATE_LIMIT,
    DEFAULT_RATE_LIMIT_STRATEGY,
    DEFAULT_RATE_LIMITS,
    LOGIN_RATE_LIMIT,
    LOGOUT_RATE_LIMIT,
    REFRESH_RATE_LIMIT,
    SEND_MESSAGE_RATE_LIMIT,
)
from app.constants.redis import (
    DEFAULT_REDIS_PORT,
    DEFAULT_SOCKET_CONNECT_TIMEOUT,
    DEFAULT_SOCKET_TIMEOUT,
)
from app.constants.sse_events import SERVICE_TO_SSE_EVENT_MAP, SSEEvent
from app.constants.validation import (
    DEFAULT_GENERATED_PASSWORD_LENGTH,
    MAX_CHECKSUM_LENGTH,
    MAX_EMAIL_LENGTH,
    MAX_MESSAGE_LENGTH,
    MAX_MIGRATION_FILENAME_LENGTH,
    MAX_PASSWORD_HASH_LENGTH,
    MAX_REFRESH_TOKEN_LENGTH,
    MAX_TITLE_LENGTH,
    MAX_TOOL_CALL_ID_LENGTH,
    MAX_TOOL_NAME_LENGTH,
    MAX_USER_NAME_LENGTH,
    MAX_UUID_LENGTH,
    MIN_PASSWORD_LENGTH,
)

__all__ = [
    # Agent
    "DEFAULT_LLM_MODEL",
    "DEFAULT_LLM_PROVIDER",
    "DEFAULT_MAX_TOKENS",
    "MAX_TITLE_LENGTH",
    "TITLE_TRUNCATION_LENGTH",
    "TITLE_TRUNCATION_SUFFIX",
    # Database
    "CLOUD_SQL_IP_TYPE_PRIVATE",
    "CLOUD_SQL_IP_TYPE_PUBLIC",
    "DEFAULT_MAX_OVERFLOW",
    "DEFAULT_POOL_SIZE",
    # HTTP
    "HTTP_BAD_REQUEST",
    "HTTP_CREATED",
    "HTTP_FORBIDDEN",
    "HTTP_INTERNAL_SERVER_ERROR",
    "HTTP_NO_CONTENT",
    "HTTP_NOT_FOUND",
    "HTTP_OK",
    "HTTP_TOO_MANY_REQUESTS",
    "HTTP_UNAUTHORIZED",
    # JWT
    "DEFAULT_ACCESS_TOKEN_EXPIRE_MINUTES",
    "DEFAULT_JWT_ALGORITHM",
    "DEFAULT_REFRESH_TOKEN_EXPIRE_DAYS",
    "HOURS_PER_DAY",
    "SECONDS_PER_DAY",
    "SECONDS_PER_HOUR",
    "SECONDS_PER_MINUTE",
    # Pagination
    "DEFAULT_PAGE",
    "DEFAULT_PER_PAGE",
    "MAX_PER_PAGE",
    "MIN_PER_PAGE",
    # Rate Limit
    "CREATE_CONVERSATION_RATE_LIMIT",
    "DEFAULT_RATE_LIMIT_STRATEGY",
    "DEFAULT_RATE_LIMITS",
    "LOGIN_RATE_LIMIT",
    "LOGOUT_RATE_LIMIT",
    "REFRESH_RATE_LIMIT",
    "SEND_MESSAGE_RATE_LIMIT",
    # Redis
    "DEFAULT_REDIS_PORT",
    "DEFAULT_SOCKET_CONNECT_TIMEOUT",
    "DEFAULT_SOCKET_TIMEOUT",
    # SSE Events
    "SERVICE_TO_SSE_EVENT_MAP",
    "SSEEvent",
    # Validation
    "DEFAULT_GENERATED_PASSWORD_LENGTH",
    "MAX_CHECKSUM_LENGTH",
    "MAX_EMAIL_LENGTH",
    "MAX_MESSAGE_LENGTH",
    "MAX_MIGRATION_FILENAME_LENGTH",
    "MAX_PASSWORD_HASH_LENGTH",
    "MAX_REFRESH_TOKEN_LENGTH",
    "MAX_TITLE_LENGTH",
    "MAX_TOOL_CALL_ID_LENGTH",
    "MAX_TOOL_NAME_LENGTH",
    "MAX_USER_NAME_LENGTH",
    "MAX_UUID_LENGTH",
    "MIN_PASSWORD_LENGTH",
]
