"""Agent/LLM configuration constants."""

# LLM Provider
DEFAULT_LLM_PROVIDER = "anthropic"
DEFAULT_LLM_MODEL = "claude-sonnet-4-5-20250929"

# Token limits
DEFAULT_MAX_TOKENS = 4096

# Conversation title generation
MAX_CONVERSATION_TITLE_LENGTH = 50
TITLE_TRUNCATION_SUFFIX = "..."
TITLE_TRUNCATION_LENGTH = 47  # MAX_CONVERSATION_TITLE_LENGTH - len(TITLE_TRUNCATION_SUFFIX)

__all__ = [
    "DEFAULT_LLM_PROVIDER",
    "DEFAULT_LLM_MODEL",
    "DEFAULT_MAX_TOKENS",
    "MAX_CONVERSATION_TITLE_LENGTH",
    "TITLE_TRUNCATION_SUFFIX",
    "TITLE_TRUNCATION_LENGTH",
]
