"""JWT authentication constants."""

# Token expiration defaults
DEFAULT_ACCESS_TOKEN_EXPIRE_MINUTES = 1440  # 1 day (24 hours)
DEFAULT_REFRESH_TOKEN_EXPIRE_DAYS = 7

# JWT algorithm
DEFAULT_JWT_ALGORITHM = "HS256"

# Time conversion constants
SECONDS_PER_MINUTE = 60
SECONDS_PER_HOUR = 3600
SECONDS_PER_DAY = 86400  # 24 * 60 * 60
HOURS_PER_DAY = 24
MS_PER_SECOND = 1000

__all__ = [
    "DEFAULT_ACCESS_TOKEN_EXPIRE_MINUTES",
    "DEFAULT_REFRESH_TOKEN_EXPIRE_DAYS",
    "DEFAULT_JWT_ALGORITHM",
    "SECONDS_PER_MINUTE",
    "SECONDS_PER_HOUR",
    "SECONDS_PER_DAY",
    "HOURS_PER_DAY",
    "MS_PER_SECOND",
]
