"""Validation constants."""

# Password validation
MIN_PASSWORD_LENGTH = 8
DEFAULT_GENERATED_PASSWORD_LENGTH = 12

# Message validation
MAX_MESSAGE_LENGTH = 32000

# User validation
MAX_USER_NAME_LENGTH = 100

# String field lengths (database schema)
MAX_EMAIL_LENGTH = 255
MAX_PASSWORD_HASH_LENGTH = 255
MAX_UUID_LENGTH = 36
MAX_TITLE_LENGTH = 255
MAX_REFRESH_TOKEN_LENGTH = 500
MAX_TOOL_CALL_ID_LENGTH = 64
MAX_TOOL_NAME_LENGTH = 100
MAX_MIGRATION_FILENAME_LENGTH = 255
MAX_CHECKSUM_LENGTH = 64  # SHA256 hex digest length

__all__ = [
    "MIN_PASSWORD_LENGTH",
    "DEFAULT_GENERATED_PASSWORD_LENGTH",
    "MAX_MESSAGE_LENGTH",
    "MAX_USER_NAME_LENGTH",
    "MAX_EMAIL_LENGTH",
    "MAX_PASSWORD_HASH_LENGTH",
    "MAX_UUID_LENGTH",
    "MAX_TITLE_LENGTH",
    "MAX_REFRESH_TOKEN_LENGTH",
    "MAX_TOOL_CALL_ID_LENGTH",
    "MAX_TOOL_NAME_LENGTH",
    "MAX_MIGRATION_FILENAME_LENGTH",
    "MAX_CHECKSUM_LENGTH",
]
